name: Scrape DOGE Website

on:
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows write access to repository content (e.g., commit files)
      actions: read  

    steps:
      - name: Set up Docker
        uses: actions/checkout@v2

      - name: Start Selenium Docker container
        run: |
          docker run -d -p 4444:4444 selenium/standalone-chrome:latest

      # Load repo and install R
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install renv 0.9.2
        run: Rscript -e "install.packages('https://cran.r-project.org/src/contrib/renv_0.9.2.tar.gz', repos = NULL, type = 'source')"
      - name: Install rcmdcheck 1.3.3
        run: Rscript -e "install.packages('https://cran.r-project.org/src/contrib/rcmdcheck_1.3.3.tar.gz', repos = NULL, type = 'source')"

      - name: Install packages
        run: |
          R -e 'install.packages("rvest")'
          R -e 'install.packages("RSelenium")'

      - name: Use RSelenium to Scrape
        run: |
          Rscript doge_scraper.R
          
      - name: Commit and Push CSV File to Repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add ./data/
          git commit -m "Latest data pull" && git push || true
